[phases.setup]
nixPkgs = ['python311', 'postgresql']
aptPkgs = ['python3-dev', 'libpq-dev']

[phases.install]
cmds = [
  'pip install -r requirements.txt'
]

[start]
cmd = "python -m streamlit run dashboard.py --server.port $PORT --server.address 0.0.0.0"
