[phases.setup]
nixPkgs = ['python311', 'postgresql', 'curl']
aptPkgs = ['python3-dev', 'libpq-dev']

[phases.install]
cmds = [
  'python3 -m venv /opt/venv',
  'curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py',
  'python3 get-pip.py',
  '/opt/venv/bin/pip install -r requirements.txt'
]

[start]
cmd = "/opt/venv/bin/python -m streamlit run dashboard.py --server.port $PORT --server.address 0.0.0.0"
