[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 -m streamlit run dashboard.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --server.enableCORS false"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.envs]
PYTHONUNBUFFERED = "1"
DATABASE_URL = "postgresql://postgres:fvPCqIuJkOHZxVtzPgmYbiYDbikhylXa@postgres.ferrovia.interno:5432/railway"
