[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
startCommand = ". /opt/venv/bin/activate && streamlit run dashboard.py --server.port $PORT --server.address 0.0.0.0"
restartPolicyType = "ON_FAILURE"

[deploy.envs]
NIXPACKS_PYTHON_VERSION = "3.11"
